name: somoim automate

on:
  schedule:
    - cron: '0 0 * * SAT'

jobs:
  schedule:
    name: cronjob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Handler
        run: python .
        env:
          pw: ${{ secrets.pw }}
          bid: ${{ secrets.bid }}
          gid: ${{ secrets.gid }}